In [2]:
 import numpy as np

In [11]:
a=np.arange(5)
b=np.random.choice(5,5,replace=False)

In [15]:
print(a,b)

[0 1 2 3 4] [1 0 4 3 2]


In [16]:
b[~np.equal(a,b)]

array([1, 0, 4, 2])

In [20]:
aux=(np.arange(5))[~np.equal(a,b)]

In [21]:
for j in aux:
    print(j)

0
1
2
4


In [27]:
one=np.ones((4,4))
one[2,:]=np.arange(4)

In [38]:
one[np.diag_indices(4)]=np.zeros(4)

In [39]:
one

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [0., 1., 0., 3.],
       [1., 1., 1., 0.]])

In [1]:
from ga import Genetic_algoruthm as ga

In [3]:
teste=ga()
teste.cost_matrix

array([[9.99000000e+02, 9.50714306e-01, 7.31993942e-01, 5.98658484e-01,
        1.56018640e-01, 1.55994520e-01, 5.80836122e-02, 8.66176146e-01,
        6.01115012e-01, 7.08072578e-01, 2.05844943e-02, 9.69909852e-01,
        8.32442641e-01, 2.12339111e-01, 1.81824967e-01, 1.83404510e-01,
        3.04242243e-01, 5.24756432e-01, 4.31945019e-01, 2.91229140e-01],
       [6.11852895e-01, 9.99000000e+02, 2.92144649e-01, 3.66361843e-01,
        4.56069984e-01, 7.85175961e-01, 1.99673782e-01, 5.14234438e-01,
        5.92414569e-01, 4.64504127e-02, 6.07544852e-01, 1.70524124e-01,
        6.50515930e-02, 9.48885537e-01, 9.65632033e-01, 8.08397348e-01,
        3.04613769e-01, 9.76721140e-02, 6.84233027e-01, 4.40152494e-01],
       [1.22038235e-01, 4.95176910e-01, 9.99000000e+02, 9.09320402e-01,
        2.58779982e-01, 6.62522284e-01, 3.11711076e-01, 5.20068021e-01,
        5.46710279e-01, 1.84854456e-01, 9.69584628e-01, 7.75132823e-01,
        9.39498942e-01, 8.94827350e-01, 5.97899979e-01, 9.2187