In [1]:
 import numpy as np

In [2]:
from ga import Genetic_algoruthm,Crossover

In [6]:
teste=Crossover(number_of_city=100,population_size=10,generations=2)

In [8]:
teste.run(crossover_function=teste.SCRX)
teste.population

array([[ 0., 40., 50., 32., 17., 57., 49.,  1., 70., 42., 83., 15.,  4.,
        58., 16., 80., 86., 14.,  8., 18., 32., 73.,  5., 37., 24., 48.,
        67., 53., 77., 54., 13., 11.,  9., 10., 59., 17., 88., 12., 73.,
         4., 29.,  2., 67., 81., 43., 75., 44., 15., 92.,  6., 62., 93.,
        64.,  6., 35., 90., 61., 28., 37., 21., 70., 85., 44., 33., 86.,
        93., 19., 95.,  8., 82., 71., 94., 79., 33., 69., 29., 77., 25.,
         7., 97., 55., 65., 68., 66., 31., 14., 11., 72., 16., 69., 92.,
        57., 41., 50., 38., 96., 30., 87., 53., 99.],
       [ 0., 40., 50., 32., 17., 57., 49.,  1., 70., 42., 83., 15.,  4.,
        58., 16., 80., 86., 14.,  8., 18., 32., 73.,  5., 37., 24., 48.,
        67., 53., 77., 54., 13., 11.,  9., 10., 59., 17., 88., 12., 73.,
         4., 29.,  2., 67., 81., 43., 75., 44., 15., 92.,  6., 62., 93.,
        64.,  6., 35., 90., 61., 28., 37., 21., 70., 85., 44., 33., 86.,
        93., 19., 95.,  8., 82., 71., 94., 79., 33., 69., 29., 77., 25

In [9]:
teste.population

array([[ 0., 40., 50., 32., 17., 57., 49.,  1., 70., 42., 83., 15.,  4.,
        58., 16., 80., 86., 14.,  8., 18., 32., 73.,  5., 37., 24., 48.,
        67., 53., 77., 54., 13., 11.,  9., 10., 59., 17., 88., 12., 73.,
         4., 29.,  2., 67., 81., 43., 75., 44., 15., 92.,  6., 62., 93.,
        64.,  6., 35., 90., 61., 28., 37., 21., 70., 85., 44., 33., 86.,
        93., 19., 95.,  8., 82., 71., 94., 79., 33., 69., 29., 77., 25.,
         7., 97., 55., 65., 68., 66., 31., 14., 11., 72., 16., 69., 92.,
        57., 41., 50., 38., 96., 30., 87., 53., 99.],
       [ 0., 40., 50., 32., 17., 57., 49.,  1., 70., 42., 83., 15.,  4.,
        58., 16., 80., 86., 14.,  8., 18., 32., 73.,  5., 37., 24., 48.,
        67., 53., 77., 54., 13., 11.,  9., 10., 59., 17., 88., 12., 73.,
         4., 29.,  2., 67., 81., 43., 75., 44., 15., 92.,  6., 62., 93.,
        64.,  6., 35., 90., 61., 28., 37., 21., 70., 85., 44., 33., 86.,
        93., 19., 95.,  8., 82., 71., 94., 79., 33., 69., 29., 77., 25

In [10]:
teste.fitness()

In [11]:
teste.fitness_pop

array([3488.02384763, 3488.72191944, 3483.66061137, 3489.48775927,
       3481.3777866 , 4350.45536318, 3511.85302456, 3492.87571016,
       3492.32955401, 3494.49871363])

In [12]:
teste.cost_matrix

array([[999.        ,  95.07143064,  73.19939418, ...,  42.75410184,
          2.54191267,  10.7891427 ],
       [  3.14291857, 999.        ,  31.43559811, ...,  89.711026  ,
         88.70864243,  77.98755459],
       [ 64.20316462,   8.4139965 , 999.        , ...,  21.58210275,
         62.28904758,   8.5347465 ],
       ...,
       [ 78.073273  ,  21.50047683,  71.56355506, ..., 999.        ,
         41.47358025,  93.03511771],
       [ 78.48829834,  20.00089211,  13.08423613, ...,  67.98181252,
        999.        ,   4.15959563],
       [  2.31106685,  37.30070999,  14.87882838, ...,  94.6707915 ,
         39.74879924, 999.        ]])