In [1]:
 import numpy as np

In [2]:
from ga import Genetic_algoruthm,Crossover

In [3]:
teste=Crossover(number_of_city=7,population_size=10,generations=100)

In [12]:
teste.run()

[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1. 3. 5. 6.]
[0. 5. 4. 1

In [10]:
teste.fitness()

In [13]:
teste.fitness_pop

array([43.66823649, 44.32805791, 42.49449981, 42.96223356, 43.64683948,
       43.81471774, 43.82954054, 44.53223498, 43.97834762, 43.83334283])

In [14]:
teste.cost_matrix

array([[999.        ,  95.07143064,  73.19939418,  59.86584842,
         15.60186404,  15.59945203,   5.80836122],
       [ 86.61761458, 999.        ,  70.80725778,   2.05844943,
         96.99098522,  83.24426408,  21.23391107],
       [ 18.18249672,  18.34045099, 999.        ,  52.47564316,
         43.19450186,  29.12291402,  61.18528947],
       [ 13.94938607,  29.21446485,  36.63618433, 999.        ,
         78.51759614,  19.96737822,  51.42344384],
       [ 59.24145689,   4.64504127,  60.75448519,  17.05241237,
        999.        ,  94.88855373,  96.56320331],
       [ 80.83973481,  30.46137692,   9.7672114 ,  68.42330265,
         44.01524937, 999.        ,  49.51769101],
       [  3.43885211,  90.93204021,  25.87799816,  66.25222844,
         31.17110761,  52.00680212, 999.        ]])